### ISSUE TITLE
Where to source new icons from?

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-WebApp#20]
I was going to add a link to the artwork source in the artwork details container as I would have found this handy a few times already. 

I thought a little button with an [link icons](https://thenounproject.com/icon/1063945/) would work well, but there is none yet in the images folder. What would be the process to add new icons / Where to source them from?

What do you think about using an icon library for this to keep them consistent and save the work for designing our own? Bootstrap recommends a few libraries: https://getbootstrap.com/docs/4.0/extend/icons/

**Comment by jmwohl** [comment]
I would defer to @ishback for this question, since he was responsible for all of the Openframe design work... any thoughts Ishac?

**Comment by jvolker** [comment]
I've contacted @ishback today and asked him for his opinion once more. 

I actually like this large icon set: 
https://material-ui.com/components/material-icons/
I like it because it's not too round and not too edgy. Feels good.

This would be an alternative but it feels a bit more corporate (too neutral/sharp) for my taste: 
https://material.io/resources/icons/?style=baseline

Even more cosy/round feel these sets. Though as they have fewer icons, I'm not sure they would give us all the ones we need:
- https://ionicons.com/
- http://demo.amitjakhu.com/dripicons/

**Comment by ishback** [comment]
Hey Jeremias, Jon,

Sorry for the late reply, I owe you an email to each of you! Will do later
this week, but didn't want to block - I also like the first icon set you
shared, we can go for this one. Thanks!

**Comment by jvolker** [comment]
@ishback Thanks for getting back to us. I'm going to create a new issue with changing the icons to https://material-ui.com/components/material-icons/.
