### ISSUE TITLE
Start from source fails

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-WebApp#5]
I tried to run the web app from source and got some errors on the terminal. The following fixed them, but there is still an error in the browser console.

1. Installing and adding the following packages to `package.json` fixed those errors:

```
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "cross-storage": "^1.0.0",
    "glslCanvas": "^0.1.7",
    "react-addons-css-transition-group": "^15.6.2",
    "react-transition-group": "^1.0.0",
```

2. Adding the following variables (taken from https://github.com/JedWatson/react-select/blob/v1.x/scss/select.scss) to `src/styles/form/CustomSelect.scss`:

```
    $select-input-bg-focus:             $select-input-bg !default;
    $select-input-box-shadow-focus:     inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 0 5px -1px fade($select-input-border-focus, 50%) !default;
    $select-input-hover-box-shadow:     0 1px 0 rgba(0, 0, 0, 0.06) !default;
    $select-menu-box-shadow:            $select-input-hover-box-shadow !default;
```
3. The web app then starts in the browser and shows `App ready.` but nothing else.  The browser console throws the following error:

```
Uncaught SyntaxError: Unexpected identifier
    at Object.<anonymous> (app.js:9049)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:595), <anonymous>:75:19)
    at Object.<anonymous> (app.js:595)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.<anonymous> (app.js:586)
    at __webpack_require__ (app.js:556)
    at app.js:579
```

How can this error be fixed?

Thanks.

**Comment by jvolker** [comment]
@jmwohl could you please check what versions of the above packages you have installed?

**Comment by jmwohl** [comment]
See PR #12
