### ISSUE TITLE
Renaming of frames not working

### ISSUE THREAD

**Issue by jvolker** [OpenframeProject/Openframe-WebApp#8]
Changing the name of a frame in the "Frame settings" doesn't work. There is no feedback or error. But next time the name appears the same in the Frames list after hitting "Save changes".

**Comment by jmwohl** [comment]
I can't seem to replicate this — when I change a Frame name and save, the name updates as expected. @jvolker is this still an issue for you? Can you provide any additional details?

**Comment by jvolker** [comment]
Just checked again. It's working for me now. 🤷‍♂️
